engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 40
        javascript:
          mass_threshold: 50
  brakeman:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  flog:
    enabled: true
    config:
      score_threshold: 50.0
  markdownlint:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true

ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
  - "**.rake"
  - "**.haml"
  - "**.js"
  - "**.md"
  - "**.scss"

exclude_paths:
- config/**/*
- spec/**/*
- vendor/**/*
- db/**/*