engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
  brakeman:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  markdownlint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
  stylelint:
    enabled: true

ratings:
  paths:
    - Gemfile.lock
    - "**.rb"
    - "**.js"
    - "**.md"
    - "**.scss"